<footer>
<div class="pull-right">
<a href="https://github.com/revolutionchain/revo-node-manager"> Revo Node Manager 2.0</a> - © 2021
</div>
<div class="clearfix"></div>
</footer>
<script type="text/javascript">
	<?php
	if($this->section === "main"){
		$section = "";
	}else{
		$section = "?p=".$this->section;
	}
	?>
	window.history.pushState("", "", "<?= $section ?>");

  const openMobileMenu = () => {
    const x = document.getElementById("mobileLinks");
    if (x.style.display === "block") {
      x.style.display = "none";
    } else {
      x.style.display = "block";
    }
}
</script>
